title: <p align="center"> Samarjit Banerjee </p>
logo: /assets/img/289899.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/saheli-das-343bb7147/">LinkedIn</a> |
  <a href="https://github.com/SaheliDas25">GitHub</a>
  
  <br>
   Senior Consultant with 3+ years of experience in Data-Science/ML Engineering Profile and overall close to 10 years of experience in Software Domain.
    Always keen to deliver high productive Software/ML solutions which enhances client/employer business satisfactions and contribute to the overall growth.
    Possess keen interest to up skill by learning new technologies which contributes to work.
  <br>
  </p>


theme: jekyll-theme-minimal
